### ISSUE TITLE
Activate/Deactivate variables (DSL)

### ISSUE THREAD

**Issue by Aniq55** [robocomp/learnbot#37]
```
activate <var_name>
deactivate <var_name>
```

`activate` sets <var_name> to True and `deactivate` sets it to False.

**Comment by pilarbachiller** [comment]
<var_name> can be a part of a condition, so these statements cannot start/terminate threads. They should only set the variables to True/False

**Comment by Aniq55** [comment]
What marks the execution and termination of threads then? @pilarbachiller

**Comment by pilarbachiller** [comment]
They are always running, but the code inside is only executed when the corresponding condition is True.

**Comment by Aniq55** [comment]
closed via #46
