### ISSUE TITLE
bug in simulator

### ISSUE THREAD

**Issue by mhaut** [robocomp/learnbot#4]
Laser and sonar are diferent. It's necessary change this.

**Comment by nikhilpandey360** [comment]
Can I take this Task?

**Comment by mhaut** [comment]
@nikhilpandey360 Thanks for your interest in the project! Are you interested in this bug only or in participating in the GSoC 2017 program?

**Comment by muskanbararia** [comment]
Can I work on it?

**Comment by mhaut** [comment]
@brickbit @Aniq55 in order to work with learnbot simulator, ultrasound interface must be included in rcis. This task is awesome to start!!! @pbustos @pilarbachiller @ljmanso

**Comment by mhaut** [comment]
@pbustos this feature is very important, could you help us? thanks!
