### ISSUE TITLE
Missing block tooltips for English language

### ISSUE THREAD

**Issue by shivanshxyz** [robocomp/learnbot#74]
In the .conf files present inside /learnbot_dsl/blocksConfig , most of the tooltips of various blocks were missing for English.

**Comment by shivanshxyz** [comment]
#73 
@ibarbech

**Comment by Spnetic-5** [comment]
Hi, I'm new to open source and really interested in contributing to robocomp, should I work on this issue?

**Comment by pilarbachiller** [comment]
Sure, you can work on it

**Comment by Spnetic-5** [comment]
I have done it and sent a PR please review it, Thanks!

**Comment by amrmoastafa** [comment]
Is there any additional thing than can be done here ?

**Comment by amrmoastafa** [comment]
is the problem still persistent ?
